import type { SessionWithConfigResponse } from '@/types';

export const mockData: SessionWithConfigResponse = {
  session_token: 'mock-dev-token-000',
  config: {
    projectId: 'mock-project',
    apiBaseUrl: '',
    button_position: 'bottom-right',
    button_offset_x: 20,
    button_offset_y: 20,
    button_type: 'icon',
    button_size: 56,
    button_color: '#000000',
    button_text_color: '#ffffff',
    button_text: '',
    button_shadow: true,
    button_animation: 'none',
    modal_width: 480,
    modal_height: 640,
    primary_color: '#000000',
    secondary_color: '#f5f5f5',
    background_color: '#ffffff',
    text_color: '#1a1a1a',
    accent_color: '#000000',
    font_family: 'Inter, sans-serif',
    stages: {
      intro: true,
      gender: true,
      parameters: true,
      measurements: true,
      belly_shape: true,
      figure_type: true,
      privacy_policy: true,
      photo_upload: true,
    },
    products: [
      {
        id: 'mock-1',
        public_id: 'mock-p1',
        name: 'Mock Jacket',
        photo_url: 'https://placehold.co/400x600/e2e8f0/1a1a1a?text=Jacket',
        thumbnail_url: 'https://placehold.co/100x100/e2e8f0/1a1a1a?text=J',
        category: 'outerwear',
        subcategory: 'Jackets',
        sku: 'MOCK-JKT-001',
        color: 'Black',
        price: 129.99,
        currency: 'USD',
        product_url: null,
        external_id: null,
        size_variants: null,
      },
      {
        id: 'mock-2',
        public_id: 'mock-p2',
        name: 'Mock Jacket',
        photo_url: 'https://placehold.co/400x600/fef3c7/1a1a1a?text=Jacket+Beige',
        thumbnail_url: 'https://placehold.co/100x100/fef3c7/1a1a1a?text=J',
        category: 'outerwear',
        subcategory: 'Jackets',
        sku: 'MOCK-JKT-001',
        color: 'Beige',
        price: 129.99,
        currency: 'USD',
        product_url: null,
        external_id: null,
        size_variants: null,
      },
      {
        id: 'mock-3',
        public_id: 'mock-p3',
        name: 'Mock Blouse',
        photo_url: 'https://placehold.co/400x600/dbeafe/1a1a1a?text=Blouse',
        thumbnail_url: 'https://placehold.co/100x100/dbeafe/1a1a1a?text=B',
        category: 'tops',
        subcategory: 'Blouses',
        sku: 'MOCK-BLS-001',
        color: 'White',
        price: 59.99,
        currency: 'USD',
        product_url: null,
        external_id: null,
        size_variants: null,
      },
      {
        id: 'mock-4',
        public_id: 'mock-p4',
        name: 'Mock Trousers',
        photo_url: 'https://placehold.co/400x600/d1fae5/1a1a1a?text=Trousers',
        thumbnail_url: 'https://placehold.co/100x100/d1fae5/1a1a1a?text=T',
        category: 'bottoms',
        subcategory: 'Trousers',
        sku: 'MOCK-TRS-001',
        color: null,
        price: 89.99,
        currency: 'USD',
        product_url: null,
        external_id: null,
        size_variants: null,
      },
      {
        id: 'mock-5',
        public_id: 'mock-p5',
        name: 'Mock Sneakers',
        photo_url: 'https://placehold.co/400x600/ede9fe/1a1a1a?text=Sneakers',
        thumbnail_url: 'https://placehold.co/100x100/ede9fe/1a1a1a?text=S',
        category: 'shoes',
        subcategory: 'Sneakers',
        sku: 'MOCK-SNK-001',
        color: null,
        price: 109.99,
        currency: 'USD',
        product_url: null,
        external_id: null,
        size_variants: null,
      },
    ],
    avatars_enabled: true,
    avatars_mode: 'both',
    logo_url: null,
    powered_by_enabled: true,
    remember_progress: false,
    language: 'auto',
  },
};
