ALTER TABLE leads
    ADD COLUMN IF NOT EXISTS auth_code VARCHAR(6),
    ADD COLUMN IF NOT EXISTS auth_code_expires_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS is_authenticated BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS auth_provider VARCHAR(20);
