import { FC, ReactNode, useState } from 'react';

import IconMoney from '@/fsd/shared/icons/IconMoney';
import IconTerm from '@/fsd/shared/icons/IconTerm';
import { TLang } from '@/fsd/shared/types/lang';
import IconComponent from '@/fsd/shared/ui/IconComponent/IconComponent';
import InputRange from '@/fsd/shared/ui/InputRange/InputRange';
import SectionTitle from '@/fsd/shared/ui/SectionTitle';

import s from './Calc.module.scss';

interface IProps {
  className?: string;
  lang: TLang;
}

const tileSection: Record<TLang, ReactNode> = {
  ru: 'Калькулятор прибыли',
  en: 'Profit Calculator'
};

const contentTitle: Record<TLang, ReactNode> = {
  ru: (
    <>
      <span>Рассчитайте увеличение ежемесячного оборота с внедрением </span>
      виджета MakeMeLook
    </>
  ),
  en: (
    <>
      <span>Calculate the increase in monthly turnover by implementation the </span>
      MakeMeLook widget
    </>
  )
};

interface ISliderSection {
  user: ReactNode;
  orders: ReactNode;
  price: ReactNode;
}

const slidersSection: Record<TLang, ISliderSection> = {
  ru: {
    user: 'Посетителей в месяц',
    orders: 'Заказов в месяц',
    price: 'Средний чек'
  },
  en: {
    user: 'Monthly users',
    orders: 'Monthly orders',
    price: 'Average order value'
  }
};

interface IResultsSection {
  extraSales: ReactNode;
  roi: ReactNode;
  cost: ReactNode;
}

const resultsSection: Record<TLang, IResultsSection> = {
  ru: {
    extraSales: 'дополнительная прибыль от использования виджета',
    roi: (
      <div>
        <span
          style={{
            display: 'block'
          }}
        >
          ROI
        </span>

        <span>окупаемость виджета</span>
      </div>
    ),
    cost: 'стоимость интеграции'
  },
  en: {
    extraSales: (
      <div>
        <span
          style={{
            display: 'block'
          }}
        >
          Extra Sales ($).
        </span>

        <span>Generated by the Widget</span>
      </div>
    ),
    roi: 'ROI in the Widget',
    cost: 'Cost of the Widget'
  }
};

const costOfWidgetUsersPrice: Record<TLang, number> = {
  ru: 10000,
  en: 200
};

interface IRange {
  min: number;
  max: number;
  step: number;
  marks: number[];
  initialValue: number;
}

const usersRange: Record<TLang, IRange> = {
  ru: {
    initialValue: 2500000,
    min: 10000,
    max: 5000000,
    step: 10000,
    marks: [10000, 2500000, 5000000]
  },
  en: {
    initialValue: 2500000,
    min: 10000,
    max: 5000000,
    step: 10000,
    marks: [10000, 2500000, 5000000]
  }
};

const ordersRange: Record<TLang, IRange> = {
  ru: {
    initialValue: 250000,
    min: 0,
    marks: [0, 250000, 500000],
    max: 500000,
    step: 200
  },
  en: {
    initialValue: 250000,
    min: 0,
    marks: [0, 250000, 500000],
    max: 500000,
    step: 200
  }
};

const priceRange: Record<TLang, IRange> = {
  ru: {
    initialValue: 25000,
    min: 0,
    marks: [0, 25000, 50000],
    max: 50000,
    step: 5
  },
  en: {
    initialValue: 1000,
    min: 0,
    marks: [0, 1000, 2000],
    max: 2000,
    step: 1
  }
};

const locales: Record<TLang, string> = {
  ru: 'ru-RU',
  en: 'en-EN'
};
const currencies: Record<TLang, string> = {
  ru: 'RUB',
  en: 'USD'
};

const formatCurrency = (amount: number, lang: TLang) =>
  new Intl.NumberFormat(locales[lang], {
    style: 'currency',
    currency: currencies[lang],
    maximumFractionDigits: 0
  }).format(amount);

const formatNumber = (amount: number, lang: TLang) =>
  new Intl.NumberFormat(locales[lang], {
    maximumFractionDigits: 2
  }).format(amount);

export const Calc: FC<IProps> = ({ lang, className }) => {
  const [usersValue, setUsersValue] = useState(usersRange[lang].initialValue);
  const [ordersValue, setOrdersValue] = useState(ordersRange[lang].initialValue);
  const [priceValue, setPriceValue] = useState(priceRange[lang].initialValue);

  const extraSales = Math.round(ordersValue * priceValue * 0.07);
  const cost = Math.round((usersValue / 10000) * costOfWidgetUsersPrice[lang]);
  const roi = Math.max(Math.round(((extraSales - cost) / cost) * 100), 0);

  return (
    <section className={`${s.sectionTitle} ${className || ''}`}>
      <SectionTitle text={tileSection[lang]} />

      <div className={s.container}>
        <h1 className={s.title2}>{contentTitle[lang]}</h1>

        <div className={s.calcContainer}>
          <div className={s.calcScaleContainer}>
            <div className={s.calcScaleItem}>
              <p>{slidersSection[lang].user}</p>

              <InputRange
                lang={lang}
                className={s.calcScale}
                item={{
                  ...usersRange[lang],
                  _value: usersValue,
                  onChange: setUsersValue
                }}
              />
            </div>

            <div className={s.calcScaleItem}>
              <p>{slidersSection[lang].orders}</p>

              <InputRange
                lang={lang}
                className={s.calcScale}
                item={{
                  ...ordersRange[lang],
                  _value: ordersValue,
                  onChange: setOrdersValue
                }}
              />
            </div>

            <div className={s.calcScaleItem}>
              <p>{slidersSection[lang].price}</p>

              <InputRange
                lang={lang}
                className={s.calcScale}
                item={{
                  ...priceRange[lang],
                  _value: priceValue,
                  onChange: setPriceValue
                }}
              />
            </div>
          </div>

          <div className={s.scaleDataContainer}>
            <div className={s.calcData}>
              <IconComponent
                icon={<IconMoney />}
                className={s.calcDataIcon}
                iconColor="#2cd1a0"
                bgColor="#edf9f6"
              />

              <div className={s.calcDataInfo}>
                <p>{formatNumber(extraSales, lang)}</p>

                <span>{resultsSection[lang].extraSales}</span>
              </div>
            </div>

            <div className={s.calcData}>
              <IconComponent
                icon={<IconTerm />}
                className={s.calcDataIcon}
                iconColor="#de63de"
                bgColor="#faeffb"
              />

              <div className={s.calcDataInfo}>
                <p>{formatNumber(roi, lang)}%</p>

                <div>{resultsSection[lang].roi}</div>
              </div>
            </div>

            <div className={s.calcData}>
              <IconComponent
                icon={<IconTerm />}
                className={s.calcDataIcon}
                iconColor="#9f73e6"
                bgColor="#f4f1fb"
              />

              <div className={s.calcDataInfo}>
                <p>{formatCurrency(cost, lang)}</p>

                <span>{resultsSection[lang].cost}</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};
